### ISSUE TITLE
Disabling TFA requires only password

### ISSUE THREAD

**Issue by therealssj** [d8-contrib-modules/tfa#38]
After you setup TFA if you wish to disable it the form asks for the user password.
After getting the user password should we try to validate it more by going through whatever validation methods the user has setup?

**Comment by nerdstein** [comment]
This is a tad confusing for me, in general.

Backing up... I see administrators specifying if they want TFA enabled for the site (maybe by role, even). I don't see the user itself having the discretion on whether or not they want TFA. 

I do see, however, that a user may need to perform their own setup for TFA actions. I still don't know or understand when a user would be asked to disable it. Can you please articulate more details of when this happens?

**Comment by therealssj** [comment]
if the user goes to his profile then under the security tab he gets the option to set up TFA.
<img width="987" alt="screen shot 2016-06-02 at 8 23 28 pm" src="https://cloud.githubusercontent.com/assets/8619106/15749461/14e6af12-2900-11e6-8549-89702b7c588c.png">

After doing the setup it looks like this
<img width="963" alt="screen shot 2016-06-02 at 8 28 56 pm" src="https://cloud.githubusercontent.com/assets/8619106/15749626/aefa23f4-2900-11e6-9ab3-d719ef46767a.png">

When the user clicks the disable link he is redirected to a new page which asks for his password and deletes all the information related to TFA for that user

**Comment by nerdstein** [comment]
OK. So, first off, we need to make this option configurable. Administrators may not want their users to be able to disable this. _We need to file a new issue_ to create a permission for "Allow disabling of my TFA". The disable feature will not show up unless a user has that permission.

But, back to your question at hand. If a user does click that, I would expect that they perform the full TFA validation operations. This is because this is how the site is expected to authenticate the user. And, if they disable it, they should be expected to perform that same operation.

**Comment by therealssj** [comment]
Okay. 
Will create a new issue for permission and use this issue for extending the validation on disabling.

**Comment by nerdstein** [comment]
Perfect

**Comment by therealssj** [comment]
Need to fix this so that a test can be written for disabling.
Skipping the test for now.
